### ISSUE TITLE
Strange result in fixed-accuracy mode

### ISSUE THREAD

**Issue by estan** [LLNL/H5Z-ZFP#1]
I'm trying the plugin out from `h5py` for the first time, and I'm having what I think is some strange results in fixed-accuracy mode. It's perfectly possible I'm doing something wrong here.

My input file looks like this:

```
estan@newton:~$ h5dump -H -p rec-0600mm-0700mm-uncompressed.hdf5
HDF5 "rec-0600mm-0700mm-uncompressed.hdf5" {
GROUP "/" {
   DATASET "reconstruction" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 500, 300, 300 ) / ( 500, 300, 300 ) }
      STORAGE_LAYOUT {
         CHUNKED ( 32, 19, 38 )
         SIZE 189267968
      }
      FILTERS {
         NONE
      }
      FILLVALUE {
         FILL_TIME H5D_FILL_TIME_ALLOC
         VALUE  0
      }
      ALLOCATION_TIME {
         H5D_ALLOC_TIME_INCR
      }
   }
   DATASET "voxel_size" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 3, 1 ) / ( 3, 1 ) }
      STORAGE_LAYOUT {
         CONTIGUOUS
         SIZE 12
         OFFSET 189378040
      }
      FILTERS {
         NONE
      }
      FILLVALUE {
         FILL_TIME H5D_FILL_TIME_IFSET
         VALUE  0
      }
      ALLOCATION_TIME {
         H5D_ALLOC_TIME_LATE
      }
   }
}
}
```

And I have this simple test program:

```python
from sys import argv
from struct import pack, unpack

import h5py

# ZFP filter number
ZFP_FILTER = 32013

# ZFP modes
ZFP_MODE_RATE = 1
ZFP_MODE_PRECISION = 2
ZFP_MODE_ACCURACY = 3
ZFP_MODE_EXPERT = 4

def zfp_rate_opts(rate):
    """Create compression options for ZFP in fixed-rate mode

    The float rate parameter is the number of compressed bits per value.
    """
    rate = pack('<d', rate)            # Pack as IEEE 754 double
    high = unpack('<I', rate[0:4])[0]  # Unpack high bits as unsigned int
    low = unpack('<I', rate[4:8])[0]   # Unpack low bits as unsigned int
    return (ZFP_MODE_RATE, 0, high, low, 0, 0)

def zfp_precision_opts(precision):
    """Create a compression options for ZFP in fixed-precision mode

    The float precision parameter is the number of uncompressed bits per value.
    """
    return (ZFP_MODE_PRECISION, 0, precision, 0, 0, 0)

def zfp_accuracy_opts(accuracy):
    """Create compression options for ZFP in fixed-accuracy mode

    The float accuracy parameter is the absolute error tolarance (e.g. 0.001).
    """
    accuracy = pack('<d', accuracy)        # Pack as IEEE 754 double
    high = unpack('<I', accuracy[0:4])[0]  # Unpack high bits as unsigned int
    low = unpack('<I', accuracy[4:8])[0]   # Unpack low bits as unsigned int
    return (ZFP_MODE_ACCURACY, 0, high, low, 0, 0)

def zfp_expert_opts(minbits, maxbits, maxprec, minexp):
    """Create compression options for ZFP in "expert" mode

    See the ZFP docs for the meaning of the parameters.
    """
    return (ZFP_MODE_EXPERT , 0, minbits, maxbits, maxprec, minexp)

def main():
    if len(argv) != 4:
        print('Usage: zfp-compress-hdf5.py <infile> <dataset> <outfile>')
        exit(1)

    with h5py.File(argv[1], 'r') as infile:
        with h5py.File(argv[3], 'w') as outfile:
            outfile.create_dataset(
                argv[2],
                data=infile[argv[2]].value,
                compression=ZFP_FILTER,
                compression_opts=zfp_accuracy_opts(0.005),
                chunks=(500, 300, 300),
                shuffle=False
            )

if __name__ == '__main__':
    main()
```

It takes an input HDF5 file, a dataset name, and creates an output HDF5 file with the given dataset name copied from the input, but compressed using zfp in fixed-accuracy mode with tolerance 0.005. Note also that I've hardcoded the HDF5 chunk size to 500x300x300, which is the exact size of my test input, to eliminate any effects of chunking compared to when using the `examples/zfp` command line tool from `zfp`.

Running it against my input produces an output file like this:

```
estan@newton:~$ h5dump -H -p rec-0600mm-0700mm-zfp.hdf5 
HDF5 "rec-0600mm-0700mm-zfp.hdf5" {
GROUP "/" {
   DATASET "reconstruction" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 500, 300, 300 ) / ( 500, 300, 300 ) }
      STORAGE_LAYOUT {
         CHUNKED ( 500, 300, 300 )
         SIZE 155369971 (1.159:1 COMPRESSION)
      }
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32013
            COMMENT H5Z-ZFP-0.3.0 (ZFP-0.5.0) github.com/LLNL/H5Z-ZFP; 
            
            PARAMS { 5242928 91252346 313532218 -1043792 -937099264 67112167 }
         }
      }
      FILLVALUE {
         FILL_TIME H5D_FILL_TIME_ALLOC
         VALUE  0
      }
      ALLOCATION_TIME {
         H5D_ALLOC_TIME_INCR
      }
   }
}
}
```

Notice how the compression ratio for the compressed dataset is just `1.159:1`, which is a lot less than what I would have expected, so I'm pretty sure I'm doing something wrong.

And sure enough, if I first extract the dataset with `h5dump` to a binary file, then compress that file with `examples/zfp` from `zfp`, passing `-f -3 500 300 300 -a 0.005` as options, I get a much better compression ratio (`3.06:1`).

So far I've been unable to see what I'm doing wrong :( First I thought I had misunderstood the `cd_values` format for the plugin, but I've verified that `zfp_stream_set_accuracy` is called with the correct tolerance (0.005).

Any ideas?

**Comment by estan** [comment]
I get a much better correspondence in the compression ratio between using `examples/zfp` and my test program above when I use the fixed-precision mode (tested with precision 10 and 12). It's just when I use the fixed-accuracy mode that I have this strange discrepancy.

**Comment by lindstro** [comment]
I suspect this is bug is caused by a missing zfp_stream_flush call after zfp_write_header in H5Z_zfp_set_local, which leaves some fixed-accuracy compression parameter bits buffered and unwritten.

**Comment by estan** [comment]
Aha, that sounds plausible. Then I shall try that out as soon as I'm at work (~30 min). Thanks for helping me debug!

**Comment by estan** [comment]
Adding a

```c
    /* Flush the ZFP stream */
    zfp_stream_flush(dummy_zstr);
```

right after the call to `zfp_write_header`, the encoded `cd_values` changes from

    PARAMS { 5242928 91252346 313532218 -1043792 -937099264 67112167 }

to

    PARAMS { 5242928 91252346 313532218 -1043792 -937099264 67636455 }

and the compression ratio is much better:

```
estan@newton:~$ h5dump -H -p ~/rec-0600mm-0700mm-zfp-rate-0-005.hdf5
HDF5 "/home/estan/rec-0600mm-0700mm-zfp-rate-0-005.hdf5" {
GROUP "/" {
   DATASET "reconstruction" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SIMPLE { ( 500, 300, 300 ) / ( 500, 300, 300 ) }
      STORAGE_LAYOUT {
         CHUNKED ( 500, 300, 300 )
         SIZE 69167859 (2.602:1 COMPRESSION)
      }
      FILTERS {
         USER_DEFINED_FILTER {
            FILTER_ID 32013
            COMMENT H5Z-ZFP-0.3.0 (ZFP-0.5.0) github.com/LLNL/H5Z-ZFP; 
            
            PARAMS { 5242928 91252346 313532218 -1043792 -937099264 67636455 }
         }
      }
      FILLVALUE {
         FILL_TIME H5D_FILL_TIME_ALLOC
         VALUE  0
      }
      ALLOCATION_TIME {
         H5D_ALLOC_TIME_INCR
      }
   }
}
}
```

So a ratio of `2.602:1`. In fact, the compressed dataset size (69167859) corresponds exactly to what I get if I first extract the dataset to a binary file with `h5dump`, and then run the `zfp` command on it with the same parameters :)

Many thanks for helping me fix this! I'll try to make a PR adding that call.

PS. The ratio of `3.06:1` I reported getting from the `zfp` earlier was in fact me misreporting, that's what I got when running `zfp` on the HDF5 file as a whole as a quick test, not what I get when running it on the `h5dump`-extracted dataset dump, which is `2.602:1`. DS.
