### ISSUE TITLE
No way to disable attempts to compile fortran interface except to have empty FC variable

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#10]
Spack defines ``FC`` variable. H5Z-ZFP uses non-empty ``FC`` as indication that fortran interface should be compiled. However, that also requires that the HDF5 library would have been compiled with its fortran features enabled. 

We need an independent switch to control whether fortran interface is compiled

**Comment by cyrush** [comment]
@markcmiller86 I have a work around for the spack package 

https://github.com/Alpine-DAV/spack/blob/task/2018_04_update_ascent/var/spack/repos/builtin/packages/h5z-zfp/package.py

Not sure when we plan to merge to spack proper yet .

**Comment by markcmiller86** [comment]
Ok, agree that current/best way to disable fortran compilation in the event ``FC`` is already defined in your enviornment is to explicitly pass an empty ``FC=`` assignment on the command-line to make. This has now been documented in H5Z-ZFP installation section.
