### ISSUE TITLE
FIles should be installed into $(DESTDIR)$(PREFIX), not just $(PREFIX)

### ISSUE THREAD

**Issue by yurivict** [LLNL/H5Z-ZFP#12]
This is a common convention to facilitate package creation. Packages are normally installed into a stage directory, that is set to ```DESTDIR``` variable when make is called.

**Comment by yurivict** [comment]
Reference: https://www.gnu.org/prep/standards/html_node/DESTDIR.html

**Comment by lindstro** [comment]
Unless I'm missing something, in this example $(DESTDIR) serves the same purpose as $(PREFIX).  Like Mark, I'm unfamiliar with the convention $(DESTDIR)$(PREFIX) and am not sure what it accomplishes that $(PREFIX) alone does not.  Can you please elaborate?

**Comment by lindstro** [comment]
Following up on my own response, perhaps I misinterpreted $(DESTDIR)$(PREFIX) to mean $(DESTDIR)/$(PREFIX).  Is the intent that only one of DESTDIR and PREFIX be defined such that their concatenation expands to $(DESTDIR)"" == $(DESTDIR) or ""$(PREFIX) == $(PREFIX)?

@yurivict Can you please supply a complete example where this mechanism is used?

**Comment by yurivict** [comment]
> Is the intent that only one of DESTDIR and PREFIX be defined such that their concatenation expands to $(DESTDIR)"" == $(DESTDIR) or ""$(PREFIX) == $(PREFIX)?

No, they are both defined and used together.

**Comment by yurivict** [comment]
You use GNU Make, GNU documentation should be treated as definitive: https://www.gnu.org/prep/standards/html_node/DESTDIR.html

Most projects are switching to ```cmake``` because GNU buildtools is itself getting obsolete, and isn't scalable. But you chose to use GNU make, so they have guidelines how to create packaging-friendly projects.

**Comment by lindstro** [comment]
I see.  So specifying PREFIX=/var/work/builder/H5Z-amd64-build/install-dir/usr/local would not work, for instance, in case an executable is built and linked against a shared object with -rpath pointing to $(PREFIX) when the shared object later is moved to /usr/local?

This seems like a reasonable fix, but a better long-term solution would be for H5Z-ZFP to use cmake, as zfp itself does.  In fact, there are features of zfp that cannot be enabled through GNU make, such as CUDA support.

@markcmiller86 Any thoughts on adopting cmake for your plugin?

**Comment by yurivict** [comment]
I've added the patch to the FreeBSD port. If your long-term solution is switching to cmake then this is fine, and can stay this way until the switch. Thanks!

**Comment by markcmiller86** [comment]
@lindstro...

regarding switching to CMake...I don't really like that approach as it introduces a new dependency. OTOH, CMake is probably as nearly ubiquitous as GNU Make at this point and so if we are careful to not use anything relatively new in CMake, we should probably be ok. 

What do you think the likelihood is to need CUDA features of ZFP when using ZFP as part of an HDF5 I/O filter? My first imprression is that this is a pretty low likelihood and so isn't a strong argument for switching to CMake. At present, I don't know if any codes expect to do file I/O operations on data in GPU memory. Do you?

**Comment by yurivict** [comment]
Running ```make DESTDIR=/tmp/some/dir install``` and checking if it is really installed into that directory should be sufficient.

**Comment by markcmiller86** [comment]
Cool. Thank you. I've got a PR that does this now. Its a tiny change and I've tested it as you described and it seems to work with DESTDIR defined and with it NOT defined. As an extra sanity check, I've asked @lindstro to review the PR.

**Comment by lindstro** [comment]
> @lindstro...
> 
> regarding switching to CMake...I don't really like that approach as it introduces a new dependency. OTOH, CMake is probably as nearly ubiquitous as GNU Make at this point and so if we are careful to not use anything relatively new in CMake, we should probably be ok.
> 
> What do you think the likelihood is to need CUDA features of ZFP when using ZFP as part of an HDF5 I/O filter? My first imprression is that this is a pretty low likelihood and so isn't a strong argument for switching to CMake. At present, I don't know if any codes expect to do file I/O operations on data in GPU memory. Do you?

@markcmiller86 I agree that using CUDA with H5Z-ZFP likely isn't too common (in fact, H5Z-ZFP does not provide a way of selecting the execution policy), though we've seen cases where doing the compression on the GPU is in fact a win, even when the data originally resides on the CPU.  It certainly makes sense to use zfp's OpenMP support on multi-core platforms.

I, too, resisted CMake for the very same reasons for a long time.  However, zfp has now gotten sufficiently complex that supporting full GNU make builds is arduous.  Getting zfp to build with CUDA, OpenMP, Python, and Fortran support on Linux, Mac OS, and Windows is quite a challenge, and we further rely on CMake's ctest for unit testing.  Finally, zfp is being integrated with larger tools and applications (ADIOS, VTK-m, Cinema, etc.), and using a single build system greatly facilitates this.

You could do what we currently do with zfp: We support GNU make for the most common cases and require CMake for everything else.

**Comment by markcmiller86** [comment]
I am not trying to argue with any of that but this all has to be placed within a context that is _relative_ to HDF5 _I/O_ operations. Remember that H5Z-ZFP is intended to be used as part of an ``H5Dwrite()`` or ``H5Dread()`` call. So, unless you have a situation where an HDF5 caller is writing to (or reading from) a _file in memory_ (which is possible with HDF5), where there are datasets compressed with zfp, I am not sure CUDA or OpenMP capabilities of ZFP are relevant. Does  single-threaded CPU only ZFP + I/O improve substantially over CUDA or OpenMP ZFP + I/O? Since I/O in both those cases is likely the dominant term, I am not sure the ZFP part is relevant.

Now, if you are thinking that being able to write and read raw ZFP compressed data (e.g. without compression or decompression) into ZFP compressed in-memory arrays via HDF5 is still important...I agree. But, I still think that is an orthogonal issue to CUDA or OpenMP features of ZFP.

But, related to this, what should we expect to happen though if we use H5Z-ZFP with a CUDA or OpenMP enabled installation of ZFP? Should that just work or is special action necessary to be taken within H5Z-ZFP in order to ensure proper behavior?

**Comment by markcmiller86** [comment]
All good points.

FWIW...any resistance to moving to CMake on my part is almost entirely based on having the resources to do it. I would welcome a PR ;)
