### ISSUE TITLE
Use H5Eregister_class correctly or remove

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#19]
At some point, I had concluded it was necessary for H5Z-ZFP to register its own error class ([H5Eregister_class()](https://portal.hdfgroup.org/display/HDF5/H5E_REGISTER_CLASS)) in order to ensure error messages from the HDF5 stack would be maximally interpretable by a user. In particular, the registered error class would include "H5Z-ZFP" in the message strings along with H5Z-ZFP version and ZFP Library version information.

However, I am not sure simply registering a new error class and using it in [H5Epush](https://portal.hdfgroup.org/display/HDF5/H5E_PUSH2) is sufficient. Documentation of [H5Epush](https://portal.hdfgroup.org/display/HDF5/H5E_PUSH2) suggests that major and minor errors *"...must be in the same class."* which suggests that more work is needed in the filter code with calls to [H5Ecreate_msg()](https://portal.hdfgroup.org/display/HDF5/H5E_CREATE_MSG) before pushing errors involving the new error class will work?

@qkoziol or @epourmal can you comment or point me in right direction?

**Comment by qkoziol** [comment]
Along with registering your new error class, you should define some major & minor errors (within it) and use those when pushing errors from H5Z-ZFP.

Apologies if the docs aren't terribly clear, I believe that you might be the first person attempting to create external error stacks... :-/

**Comment by markcmiller86** [comment]
So, if I understand things, I am not creating a new "stack"; just a new error class which I believe can live harmoniously on the same stack. Correct?

What if I wanna use all the standard major/minor error messages that are used for example in H5Zszip.c and just have them pre-ambled with H5Z-ZFP name and version info? That seems to mean I have to re-create those same messages here for the new error class? So, maybe it is best to NOT create a new error class and just use H5E_ERR_CLS? But, if I do that, then I loose the ability to indicate that these errors are comming from either ZFP library or H5Z-ZFP plugin.

**Comment by qkoziol** [comment]
Yes, that's correct - it'll be on the same error stack.

And yes, that's a possible downside to the way the public error interface works.  :-/

**Comment by markcmiller86** [comment]
Thanks Q, I appreciate the help!
