### ISSUE TITLE
Disallow invalid dimension sizes

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#28]
See https://github.com/LLNL/zfp/issues/45

H5Z-ZFP should provide a useful error message.

**Comment by lindstro** [comment]
Agreed.  I'm hoping to address this in zfp_write_header for 0.5.5, as this function should not succeed for such arrays.  Are you already checking its return value?  It ought to return zero upon failure.

**Comment by markcmiller86** [comment]
Yes, I do check return value. But, I'd like to be able to be as specific as I can in an error message about *why* an operation failed as well ;). For example, to detect codec mismatch in `zfp_read_header`, I need to read header with *only* the magic mask set as currently, a zero return from that operation is only possible upon codec mismatch. If I do this with FULL mask, I cannot distinguish failure mode. That is fine. I might just need to *probe* the header with multiple calls to `zfp_write_header` with different masks and `zfp_stream_rewind` in between.

**Comment by lindstro** [comment]
I agree that it would be nice to get better feedback on what went wrong.  I've entertained the idea of adding error codes to zfp (along the lines of `errno`).  Doing this correctly would require some effort, and I don't expect we'll have time soon to address this.  I'm open to any other suggestions you might have.

**Comment by markcmiller86** [comment]
I do check return value of `zfp_write_header` and issue a generic error message.

I think for the period of time until this problem is resolved in ZFP library itself, this is sufficient and so am closing this issue,
