### ISSUE TITLE
'include/make.vars.inc' is referring to the stage directory

### ISSUE THREAD

**Issue by yurivict** [LLNL/H5Z-ZFP#37]
The contents of the installed ```make.vars.inc```:
```
ZFP_HOME=/usr/ports/science/h5z-zfp/work/stage/usr/local HDF5_HOME=/usr/ports/science/h5z-zfp/work/stage/usr/local PREFIX=/usr/local
```

Stage directory is ```/usr/ports/science/h5z-zfp/work/stage```. No installed files can contain the stage directory.

Version ```1.0.0```.

**Comment by markcmiller86** [comment]
> No installed files can contain the stage directory.

@yurivict where is this policy coming from?

Honestly, I had forgotten I had logic in there to produce it. Maybe I should just remove this feature entirely? The point of this file is to record the paths to the dependencies used to build it.

**Comment by yurivict** [comment]
> where is this policy coming from?

This is common sense. The stage directory is a temporary directory that is deleted after the installation, so when installed files still contain it this is obviously wrong.

**Comment by markcmiller86** [comment]
> The stage directory is a temporary directory that is deleted after the installation

Well, why did you use a *stage* directory for your paths to the ZFP and HDF5 libraries when you set `ZFP_HOME` and `HDF5_HOME`?

I mean, presumably you installed ZFP and HDF5 somwhere other than your *stage* directory. If so, use those paths to build H5Z_ZFP and then `make.vars.inc` would contain paths to the install points for those packages and not the stage used for those packages.

Am I missing something here?

**Comment by yurivict** [comment]
This is in the standard ports framework.
Everything is installed into /usr/local but during build and installation they are installed into another directory /path/to/stage/usr/local, from where they are later packaged. Naturally, /path/to/stage is not supposed to occur in the installed files, and it does in your project, which is a bug.
