### ISSUE TITLE
Fix duplication of compile-time version info

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#40]
Compile-time version number information is duplicated in `H5Zzfp_plugin.h` and `H5Zzfp_props_f.F90`. 

@brtnfld is there any reason `H5Zzfp_props_f.F90` shouldn't just include `H5Zzfp_plugin.h`. Maybe I should create a header file that has only that information in it and nothing else?

**Comment by brtnfld** [comment]
I'm not sure how you can do this without using a build time parameter to distinguish the Fortran and C syntax.

You can't do this, which uses the C #define syntax header:

MODULE mod
  INCLUDE "a.h"
  INTEGER, PARAMETER :: C = XX

where a.h is:
#define XX 6

You can do 

MODULE mod
#define XX XX_C
  INTEGER, PARAMETER :: C = XX

gfortran -DXX_C=6

but that does not help.

**Comment by brtnfld** [comment]
Duh, you can use #include instead. You can replace all the other common constants this way as well to avoid duplicate code.

**Comment by markcmiller86** [comment]
Ok, thanks. Will try to do that on another pass later this summer.

**Comment by markcmiller86** [comment]
@brtnfld I think I should tackle this too for this upcomming release of H5Z-ZFP. Thoughts?

**Comment by brtnfld** [comment]
That would be great!

**Comment by markcmiller86** [comment]
Unfortunately, this isn't as easy as [above](https://github.com/LLNL/H5Z-ZFP/issues/40#issuecomment-507730072) would suggest because we're using the *identical* identifier names in both C and Fortran code. So, the CPP macro identifier names collide with the Fortran parameter names. 

I think the right answer is to somehow *munge* the CPP macro identifier names when the get included in the Fortran module for properties and the only way I've currently found to do that is to basically duplicate all the symbols in `H5Zzfp_props.h` unmunged and then munged in a conditional compilation code block. Not very satisfying though it does possibly make it a little more obvious to any programmer that version information is codified in two places.

**Comment by markcmiller86** [comment]
Ok, I have a fix for this. Have a look at https://github.com/LLNL/H5Z-ZFP/commit/f940cec5ea964f56d90d9dd662293e1c097973de

 It isn't too pretty but I don't think its too bad either.

**Comment by brtnfld** [comment]
Looks good, thanks!
