### ISSUE TITLE
h5repack does not work with ZFP

### ISSUE THREAD

**Issue by leighorf** [LLNL/H5Z-ZFP#53]
I just posted this to the HDF5 user group, as it touches both hdf5 and zfp.

https://forum.hdfgroup.org/t/h5repack-not-working-for-zfp-filter-id-32012/8702

Short description: When using h5repack with the user defined ZFP filter, it fails with "Error occurred while repacking"

The plugin has been determined to work with h5dump on zfp compressed data, so I don't think it's the plugin itself but maybe how it's being used by h5repack. There is an old patch that can no longer be applied to h5repack (https://github.com/LLNL/H5Z-ZFP/blob/master/test/h5repack_parse.patch) that doesn't look like it ever made its way into the mainline code. However this patch can no longer be applied, as it was from 2015.

**Comment by markcmiller86** [comment]
@leighorf thanks for the report. Out of curiosity, did you have a look at [these docs](https://h5z-zfp.readthedocs.io/en/latest/h5repack.html) and find them to be unhelpful?

**Comment by leighorf** [comment]
Yes, to a point.

On that page I see things like:

$(HDF5_BIN)/h5repack -f UD=32013,4,1,0,0,1074921472

which lacks the magical 0/1 flag that indicates whether the plugin is
"mandatory" or "optional".

It should read:

 $(HDF5_BIN)/h5repack -f UD=32013,*0*,4,1,0,0,1074921472

This is the problem. There is no documentation that I know of that contains
that extra flag, and the error reporting for h5repack is... lacking.

Leigh

**Comment by markcmiller86** [comment]
Thanks. I think I've handled H5Z-ZFP end of things with #54 update.
