### ISSUE TITLE
memory errors with H5Z-ZFP on 1.12.0 with free() but not H5MM_xfree()

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#61]
Running on macOS 10.14.6 (Mojave) and HDF5 1.12.0 I am seeing memory errors at this line, https://github.com/LLNL/H5Z-ZFP/blob/497e94204db6579a92b728e13aec699e76cb8f96/src/H5Zzfp.c#L628

but only using the filter as a lib, not a dynamic plugin. And, if I switch `free()` to `H5MM_xfree()` that fixes it.

```
test_write_lib(7783,0x11a8be5c0) malloc: *** error for object 0x7fcfe2023230: pointer being freed was not allocated
test_write_lib(7783,0x11a8be5c0) malloc: *** set a breakpoint in malloc_error_break to debug
/bin/bash: line 1:  7783 Abort trap: 6           ./test_write_lib rate=$r zfpmode=1 2>&1 > /dev/null
HDF5-DIAG: Error detected in HDF5 (1.12.0) thread 0:
  #000: ../../src/H5F.c line 793 in H5Fopen(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #001: ../../src/H5VLcallback.c line 3500 in H5VL_file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #002: ../../src/H5VLcallback.c line 3465 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #003: ../../src/H5VLnative_file.c line 100 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #004: ../../src/H5Fint.c line 1716 in H5F_open(): unable to read root group
    major: File accessibility
    minor: Unable to open file
  #005: ../../src/H5Groot.c line 239 in H5G_mkroot(): can't check if symbol table message exists
    major: Symbol table
    minor: Can't get value
  #006: ../../src/H5Omessage.c line 883 in H5O_msg_exists(): unable to protect object header
    major: Object header
    minor: Unable to protect metadata
  #007: ../../src/H5Oint.c line 1082 in H5O_protect(): unable to load object header
    major: Object header
    minor: Unable to protect metadata
  #008: ../../src/H5AC.c line 1312 in H5AC_protect(): H5C_protect() failed
    major: Object cache
    minor: Unable to protect metadata
  #009: ../../src/H5C.c line 2346 in H5C_protect(): can't load entry
    major: Object cache
    minor: Unable to load metadata into cache
  #010: ../../src/H5C.c line 6689 in H5C_load_entry(): incorrect metadatda checksum after all read attempts
    major: Object cache
    minor: Read failed
  #011: ../../src/H5Ocache.c line 220 in H5O__cache_get_final_load_size(): can't deserialize object header prefix
    major: Object header
    minor: Unable to decode value
  #012: ../../src/H5Ocache.c line 1232 in H5O__prefix_deserialize(): bad object header version number
    major: Object header
    minor: Wrong version number
H5Fopen failed at line 144
Library rate test failed for rate=32
make[1]: *** [test-lib-rate] Error 1
make: *** [check] Error 2
[scratlantis:~/silo/zfp_filter/H5Z-ZFP] miller86% lldb test/test_write_lib
(lldb) target create "test/test_write_lib"
Current executable set to 'test/test_write_lib' (x86_64).
(lldb) run rate=8 zfpmode=1
Process 7827 launched: '/Users/miller86/silo/zfp_filter/H5Z-ZFP/test/test_write_lib' (x86_64)
    ifile=""                                  set input filename
    ofile="test_zfp.h5"                      set output filename
    
1D dataset generation arguments...
    npoints=1024             set number of points for 1D dataset
    noise=0.001         set amount of random noise in 1D dataset
    amp=17.7             set amplitude of sinusoid in 1D dataset
    chunk=256                      set chunk size for 1D dataset
    doint=0                              also do integer 1D data
    
ZFP compression paramaters...
    zfpmode=1        (1=rate,2=prec,3=acc,4=expert,5=reversible)
    rate=8                                set rate for rate mode
    acc=0                         set accuracy for accuracy mode
    prec=11                     set precision for precision mode
    minbits=0                        set minbits for expert mode
    maxbits=4171                     set maxbits for expert mode
    maxprec=64                       set maxprec for expert mode
    minexp=-1074                      set minexp for expert mode
                            
Advanced cases...
    highd=0                                          run 4D case
    sixd=0          run 6D extendable case (requires ZFP>=0.5.4)
    help=0                                     this help message
test_write_lib(7827,0x1000ec5c0) malloc: *** error for object 0x101026e30: pointer being freed was not allocated
test_write_lib(7827,0x1000ec5c0) malloc: *** set a breakpoint in malloc_error_break to debug
Process 7827 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00007fff590ff2c2 libsystem_kernel.dylib`__pthread_kill + 10
libsystem_kernel.dylib`__pthread_kill:
->  0x7fff590ff2c2 <+10>: jae    0x7fff590ff2cc            ; <+20>
    0x7fff590ff2c4 <+12>: movq   %rax, %rdi
    0x7fff590ff2c7 <+15>: jmp    0x7fff590f9453            ; cerror_nocancel
    0x7fff590ff2cc <+20>: retq   
Target 0: (test_write_lib) stopped.
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
  * frame #0: 0x00007fff590ff2c2 libsystem_kernel.dylib`__pthread_kill + 10
    frame #1: 0x00007fff591babf1 libsystem_pthread.dylib`pthread_kill + 284
    frame #2: 0x00007fff590696a6 libsystem_c.dylib`abort + 127
    frame #3: 0x00007fff59178077 libsystem_malloc.dylib`malloc_vreport + 545
    frame #4: 0x00007fff59177e38 libsystem_malloc.dylib`malloc_report + 151
    frame #5: 0x0000000100008ec1 test_write_lib`H5Z_filter_zfp(flags=0, cd_nelmts=4, cd_values=0x0000000100b6bfe8, nbytes=2048, buf_size=0x00007ffeefbfe158, buf=0x00007ffeefbfe200) at H5Zzfp.c:628:9
    frame #6: 0x00000001008595a0 libhdf5.200.dylib`H5Z_pipeline(pline=0x000000010100a4c0, flags=0, filter_mask=0x00007ffeefbfe1a8, edc_read=H5Z_ENABLE_EDC, cb_struct=H5Z_cb_t @ 0x00007ffeefbfe040, nbytes=0x00007ffeefbfe150, buf_size=0x00007ffeefbfe158, buf=0x00007ffeefbfe200) at H5Z.c:1366:26
    frame #7: 0x000000010022a80b libhdf5.200.dylib`H5D__chunk_flush_entry(dset=0x0000000100b692a0, ent=0x0000000100b6e630, reset=false) at H5Dchunk.c:3413:16
    frame #8: 0x0000000100222ccf libhdf5.200.dylib`H5D__chunk_flush(dset=0x0000000100b692a0) at H5Dchunk.c:2824:12
    frame #9: 0x0000000100271150 libhdf5.200.dylib`H5D__flush_real(dataset=0x0000000100b692a0) at H5Dint.c:3233:50
    frame #10: 0x000000010026feca libhdf5.200.dylib`H5D_close(dataset=0x0000000100b692a0) at H5Dint.c:1920:12
    frame #11: 0x000000010083930d libhdf5.200.dylib`H5VL__native_dataset_close(dset=0x0000000100b692a0, dxpl_id=792633534417207304, req=0x0000000000000000) at H5VLnative_dataset.c:634:8
    frame #12: 0x0000000100802e88 libhdf5.200.dylib`H5VL__dataset_close(obj=0x0000000100b692a0, cls=0x0000000100b1d540, dxpl_id=792633534417207304, req=0x0000000000000000) at H5VLcallback.c:2595:8
    frame #13: 0x0000000100802a9c libhdf5.200.dylib`H5VL_dataset_close(vol_obj=0x0000000100b69150, dxpl_id=792633534417207304, req=0x0000000000000000) at H5VLcallback.c:2633:8
    frame #14: 0x000000010027c003 libhdf5.200.dylib`H5D__close_cb(dset_vol_obj=0x0000000100b69150) at H5Dint.c:352:8
    frame #15: 0x0000000100452864 libhdf5.200.dylib`H5I_dec_ref(id=360287970189639681) at H5I.c:1376:41
    frame #16: 0x0000000100452535 libhdf5.200.dylib`H5I_dec_app_ref(id=360287970189639681) at H5I.c:1421:21
    frame #17: 0x00000001004529f5 libhdf5.200.dylib`H5I_dec_app_ref_always_close(id=360287970189639681) at H5I.c:1465:17
    frame #18: 0x0000000100209d7e libhdf5.200.dylib`H5Dclose(dset_id=360287970189639681) at H5D.c:337:8
    frame #19: 0x0000000100003449 test_write_lib`main(argc=3, argv=0x00007ffeefbff7f8) at test_write.c:456:13
    frame #20: 0x00007fff58fc43d5 libdyld.dylib`start + 1
    frame #21: 0x00007fff58fc43d5 libdyld.dylib`start + 1
(lldb) frame 5
invalid command 'frame 5'.
(lldb) up 5
frame #5: 0x0000000100008ec1 test_write_lib`H5Z_filter_zfp(flags=0, cd_nelmts=4, cd_values=0x0000000100b6bfe8, nbytes=2048, buf_size=0x00007ffeefbfe158, buf=0x00007ffeefbfe200) at H5Zzfp.c:628:9
   625 	        if (zsize > msize)
   626 	            H5Z_ZFP_PUSH_AND_GOTO(H5E_RESOURCE, H5E_OVERFLOW, 0, "uncompressed buffer overrun");
   627 	
-> 628 	        free(*buf);
   629 	        *buf = newbuf;
   630 	        newbuf = 0;
   631 	        *buf_size = zsize;
```

@brtnfld do you have any ideas?

**Comment by jwsblokland** [comment]
@markcmiller86 I do have a small question. What kind of HDF5 1.12.0 version have you been using? I mean, is it a release or debug version? If I remember it correctly, HDF5 does all kind of special things regarding the memory allocation when you use the debug version.

When you use the filter as a lib, it does make senses to me to fully switch to HDF5 memory management since this case the filter has become more or less part of the HDF5 library itself. However, I can image the code becomes a bit more complex due to the difference between a library and a plugin build.

**Comment by derobins** [comment]
I'd be willing to bet that the problem is due to our memory allocation sanity checks. When those are turned on, we add canaries to each allocated buffer. We do this by allocating a larger buffer, writing in the leading/trailing canaries and returning a pointer inside the buffer. If you try to free this pointer, the memory allocator will complain.

The solution in this case is to simply turn off the memory sanity checks using --disable-memory-alloc-sanity-check (Autotools) or by turning off HDF5_MEMORY_ALLOC_SANITY_CHECK (CMake). The sanity checks should only be switched on by default in debug builds of the library. Release branches/tags will build with production/release settings by default, but all other branches will build with debug settings.

Alternatively, you could use H5allocate_memory(), H5resize_memory(), and H5free_memory() when working with filters as those will use our memory allocators, but those should really only be necessary on Windows or if you are linking to an external allocator like dmalloc.

**Comment by markcmiller86** [comment]
> I'd be willing to bet that the problem is due to our memory allocation sanity checks.

So, just to be clear...the *problem* is occuring when I am **NOT** using HDF5's `H5MM_xfree()` to free memory in the compressor. That would suggest that the pointer HDF5 is handing the filter is something that was internally adjusted (maybe due precisely to its internal memory allocation sanity checks) and not one returned from a call to `malloc()`. Am I understanding that correctly?

And, it sounds like the solution is to adjust how HDF5-1.12.0 is configured to disable that internal memory allocation sanity checking.

**Comment by markcmiller86** [comment]
Ok, thanks @derobins. I have indeed re-configured HDF5-1.12.0 with `--disable-memory-alloc-sanity-check` and that has fixed the problem.

**Comment by brtnfld** [comment]
Is there a way to tell in what mode HDF5 was built from the installation files?

**Comment by markcmiller86** [comment]
Hmm...I guess maybe check to see how `H5MM_x...()` funcs are defined? Good idea though. I guess I can go look at the header files. But, I worry anything I find there will be *implementation* defined and vulnerable to changes with updates to HDF5.

**Comment by brtnfld** [comment]
It is tricky because on the one hand it would be nice to skip the test if HDF5 was built in Debug mode (mainly for CI testing), but it would also be useful for a user to know that there could be an issue with the HDF5 build. It is not at all obvious from the error what the problem could be, it should probably be documented as a known issue.

**Comment by derobins** [comment]
Starting in HDF5 1.12.1 we're going to be switching the memory sanity checks off in release branches for both debug and production. 1.10.7 did not have this change, but 1.10.8 will.

**Comment by markcmiller86** [comment]
> Is there a way to tell in what mode HDF5 was built from the installation files?

It looks like this CPP symbol, `H5_MEMORY_ALLOC_SANITY_CHECK`, is defined when `--disable-memory-alloc-sanity-check` is specified during `configure`. 

The only choices I see to add logic to check for how HDF5 library was configured are either compile time of H5Z-ZFP or run time of H5Z-ZFP. Using compile time would alert user only to the installation of HDF5 library headers H5Z-ZFP was compiled with. That may or may not be the same installation used by a client application using H5Z-ZFP as either a plugin (or library). So, I think the only conceivable way is to do it at run-time of H5Z-ZFP. So, is here a (cheap) calling sequence into public parts of HDF5 library that would reveal whether the lib was configured with `--disable-memory-alloc-sanity-check`? I don't know the answer. I think someone who knows HDF5 lib internals and some creativity might be able to.

However, this all sounds like a bit of a stretch too. Thoughts?

**Comment by epourmal** [comment]
I don't think there is any calling sequence into public APIs. Maybe the info below could help?

There is a way to find out from `libhdf5.settings `file or  `libhdf5.a` file if memory allocation sanity checks are on or off. 

`libhdf5.settings` file in the installation directory (where `libhdf5.a(so)` is) will contain at the very end 
```
Features
---------
...
   Memory allocation sanity checks: no
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: no
      Optimization instrumentation: no
```
  One can use `strings` command on  libhdf5.a file (we jam configuration summary into the library file)
```
strings libhdf5.a | grep "Memory"
   Memory allocation sanity checks: no  
```
**When sanity checks are not disabled (for example, in the current HDF5 develop branch), one will get**
```
Features
---------
...
   Memory allocation sanity checks: yes
            Function stack tracing: no
                  Use file locking: best-effort
         Strict file format checks: yes
      Optimization instrumentation: no
```

```
strings libhdf5.a | grep "Memory"
   Memory allocation sanity checks: yes
```

Also, installed H5pubconh.h will contain

`H5pubconf.h:#define H5_MEMORY_ALLOC_SANITY_CHECK 1`

**Comment by markcmiller86** [comment]
@epourmal thanks for this info! It is very good to know. 

Unfortunately, however, it doesn't help with this issue because a) it needs to work from within an executing C program, b) it needs to be very low cost and c) it needs to work when H5Z-ZFP is being used as a plugin. The plugin could have been compiled with one installation of `libhdf5.so` but ultimately be used within an application using a different (but nonetheless ABI compatible) installation of `libhdf5.so`.

I was thinking that if the sanity checking stuff in HDF5 stuffed some magic bytes or something in memory *ahead* of the returned pointer and there was some simple call that caused HDF5 to exercise its memory allocator and return something, I could then maybe probe memory locations just ahead of the returned pointer for that magic stuff.
