### ISSUE TITLE
Add  testing for CMake builds.

### ISSUE THREAD

**Issue by brtnfld** [LLNL/H5Z-ZFP#64]
Testing is missing for CMake builds.

**Comment by jwsblokland** [comment]
I have started working on implementing some CMake tests based on Make tests. I see already there are some tricky details to get everything to work. Nevertheless, I am hopeful that all the Make tests can be converted to CMake tests.

**Comment by jwsblokland** [comment]
In pull request #89 I have added several CMake tests. Most of them work on any platform. Or at least they should. Some of them only work on a Unix-like system.

**Comment by brtnfld** [comment]
We finally have all the kinks worked out for adding CMake testing. Thank you to everyone that contributed to this!

PR #116
