### ISSUE TITLE
autotools testing build fails with current zfp

### ISSUE THREAD

**Issue by brtnfld** [LLNL/H5Z-ZFP#73]
In congfig.make 

ZFP_HAS_CFP := $(shell grep '^BUILD_CFP' $(ZFP_HOME)/Config | tr -d ' ' | cut -d'=' -f2)

but "Config" is not part of the zfp installation.

**Comment by markcmiller86** [comment]
Hmm...well [`Config`](https://github.com/LLNL/zfp/blob/develop/Config) is part of ZFP *build*. How can one test if ZFP was *built with* CFP? Maybe only method is if ZFP was installed with CMake?

**Comment by markcmiller86** [comment]
@lindstro if ZFP is built *manually* (e.g. not with CMake) is there any way from looking at what gets installed with `make install` whether CFP was enabled or not?

**Comment by brtnfld** [comment]
This is a cmake ZFP build. I'm changing it to see if libcfd* exists instead.

**Comment by markcmiller86** [comment]
> I'm changing it to see if libcfd* exists instead.

Ah, ok. My mistake in H5Z-ZFP's config logic then. Sorry.

**Comment by lindstro** [comment]
@markcmiller86 The correct answer is provided by @brtnfld, i.e., see if `libcfp.*` gets built.  But I don't see how this has any relevance to H5Z-ZFP.  libcfp is a set of C wrappers around the C++ compressed-array classes that should not be used by H5Z-ZFP.

**Comment by markcmiller86** [comment]
@lindstro it is there to deal with this test, https://github.com/LLNL/H5Z-ZFP/blob/5a724ffab927a63c483e37017b05a8eb57e574f9/test/test_write.c#L594

So, you're right. I don't think H5Z-ZFP installs any differently but I don't want that test code to get enabled if ZFP wasn't installed with the requisite support.

**Comment by brtnfld** [comment]
Fixed.
