### ISSUE TITLE
H5Z-ZFP ought to use ZFP_VERSION_PATCH as ZFP_VERSION_RELEASE

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/H5Z-ZFP#77]
I believe this change to `ZFP_VERSION_RELEASE` is a mistake. @GarrettDMorrison can you please comment?  Going forward, I think H5Z-ZFP ought to use `ZFP_VERSION_PATCH` as `ZFP_VERSION_RELEASE` exists only for backwards compatibility.

_Originally posted by @lindstro in https://github.com/LLNL/zfp/issues/160#issuecomment-1090367686_

**Comment by jwsblokland** [comment]
Hello @markcmiller86 

I have created a pull request to address this issue. The pull request is https://github.com/LLNL/H5Z-ZFP/pull/79.

Best regards,
Jan-Willem

**Comment by jwsblokland** [comment]
I just saw that you already created a pull request yourself therefore I have abandoned mine.
