### ISSUE TITLE
H5Z-ZFP in combination with zfp 1.0.0: unable to build due to moved header file bitstream.h

### ISSUE THREAD

**Issue by jwsblokland** [LLNL/H5Z-ZFP#81]
The other day, I tried to build (cmake) H5Z-ZFP using branch [mcm86-06apr22-use-zfp-vers-patch](https://github.com/LLNL/H5Z-ZFP/tree/mcm86-06apr22-use-zfp-vers-patch) while using zfp 1.0.0 (has been build using cmake)  but unfortunately I did not succeed. The reason of the failure is that the header file bitstream.h of zfp has been moved from include to include/zfp resulting in compilation error at line 42 of H5Zzfp.c. I noticed that for both zfp 0.5.5 and 1.0.0 the file bitstream.h has been included by zfp.h. This makes me wonder could we safely remove the inclusion of bitstream.h (line 42) or is it necessary for an older version of zfp?

Note that pull request https://github.com/LLNL/H5Z-ZFP/pull/78 and https://github.com/LLNL/H5Z-ZFP/pull/80 are related to support zfp 1.0.0.

**Comment by jwsblokland** [comment]
I got a similar error when using the provided build instruction using make.

**Comment by brtnfld** [comment]
bitstream.h has been in zfp.h since zfp 0.4.0, so it can be removed. 
zfp.h can also be pulled out of the #ifdef.
Also @markcmiller86, defining AS_SILO_BUILTIN does not work and results in compilation errors.

**Comment by markcmiller86** [comment]
Ok, we'll get these issues fixed by end of week. Very busy with tons of meetings at the moment 😉

**Comment by markcmiller86** [comment]
> Also @markcmiller86, defining AS_SILO_BUILTIN does not work and results in compilation errors.

@brtnfld compiling with `-DAS_SILO_BUILTIN` here is actually not appropriate and I would expect could or might fail. Or, more correctly, I don't think I care if it does. What I care about is whether compiling `H5Zzfp.c` with `-DAS_SILO_BUILTIN` works when it is compiled *within* the Silo library. And, that does work. It requires an adjusted `zfp.h` to work correctly because the entire ZFP interface is compiled with `static` (so no ZFP symbols are available in the global namespace).

I will update the documentation to be a little clearer about this.

**Comment by jwsblokland** [comment]
I just noticed that ZFP_VERSION_RELEASE does not exist anymore in zfp 1.0.0. Instead we should make use of ZFP_VERSION_PATCH.

The rejected pull request https://github.com/LLNL/H5Z-ZFP/pull/78 contains an implementation which can handle this properly for both zfp 0.5.x and 1.0.0. At least that is my impression.

**Comment by markcmiller86** [comment]
> I just noticed that ZFP_VERSION_RELEASE does not exist anymore in zfp 1.0.0. Instead we should make use of ZFP_VERSION_PATCH.
> 
> The rejected pull request #78 contains an implementation which can handle this properly for both zfp 0.5.x and 1.0.0. At least that is my impression.

#78 was a poor solution as it used special knowledge of ZFP internal CPP symbols. ZFP developers advised to use `ZFP_VERSION_STRING` instead. That is what #80 does, and so #78 was closed in favor of #80.

All that said, ZFP-1.0.0 is now released and updates here may be required to support it. I planned on getting to that this past week. It will be a bit longer though.

**Comment by markcmiller86** [comment]
Have a look at #85 (which is still a draft PR but close I think)

**Comment by jwsblokland** [comment]
@markcmiller86, I took a quick look at the code and tried to compile (GNU make) it using a vanilla build of zfp 0.5.5 and 1.0.0. Unfortunately, I did encounter some minor problems when compiler test_write.c which can be easily fixed. A proposed fix is part of the two small comments I made to your draft pull request.

**Comment by markcmiller86** [comment]
@jwsblokland thanks for taking a look.

I fixed issues you found now but realize I need to test something due to change to 4 hex digit version numbering scheme. I need to make sure it can successfully read and decompress data stored from older H5Z-ZFP using a 3 hex digit version numbering scheme.
