### ISSUE TITLE
ZFP-filter seems unable to compress the data in hdf5 file

### ISSUE THREAD

**Issue by disheng222** [LLNL/H5Z-ZFP#88]
Hi, 
I am testing HDF5 filter but encountered the problem. 
The generated .zfp.h5 file always has the same as as the original .h5 file. 
I am sure that the HDF5_PLUGIN_PATH is set correctly and the zfp's plugin .so file is able to be found in this path. The version of HDF5 library should be fine too (I tested 1.10.3, 1.10.7 and 1.12.1), because I can use this version to run other filters such as H5Z_SZ correctly. 
Any ideas? 

I described the detailed settings as follows: 
I used the following command to compile H5Z-ZFP: 

make CC=gcc HDF5_HOME=/home/sdi/Install/hdf5-1.10.3-install ZFP_HOME=/home/sdi/Development/zfp/zfp-0.5.4/zfp PREFIX=/home/sdi/Install/H5Z-ZFP-install all
make CC=gcc HDF5_HOME=/home/sdi/Install/hdf5-1.10.3-install ZFP_HOME=/home/sdi/Development/zfp/zfp-0.5.4/zfp PREFIX=/home/sdi/Install/H5Z-ZFP-install install

Then, /home/sdi/Install/H5Z-ZFP-install has been put in the HDF5_PLUGIN_PATH. 
For example: 
[sdi@localhost H5Z-ZFP]$ echo $HDF5_PLUGIN_PATH
/home/sdi/Install/sz-2.1.12-install/lib:/home/sdi/Install/H5Z-ZFP-install/plugin:/home/sdi/Development/H5Z/H5Z-SZ3/SZ3/build/sz3-install/lib64
Then, 
[sdi@localhost test]$ h5repack -f UD=32013,0,4,1,0,0,1074528256 -i mesh.h5 -o mesh.zfp.h5
[sdi@localhost test]$ ls -al mesh.*
-rw-rw-r-- 1 sdi sdi 1151188 Aug 18 16:08 mesh.h5
-rw-rw-r-- 1 sdi sdi 1152003 Aug 19 16:29 mesh.zfp.h5
[sdi@localhost test]$ 
The size is not reduced at all.

**Comment by markcmiller86** [comment]
I suspect it is skipping running the plugin entirely. How did you [compile ZFP](https://h5z-zfp.readthedocs.io/en/latest/installation.html#compiling-zfp)? Did you set `-DBIT_STREAM_WORD_TYPE` to `uint8`?

**Comment by disheng222** [comment]
Yes. This is the reason. I didn't set BIT_STREM_WORD_TYPE. Thanks.

**Comment by markcmiller86** [comment]
Ok, thanks for letting us know :wink:.

The filter does indeed detect this condition and issue an error messages via HDF5's error stack interface.

But, HDF5 tools like `h5repack` are not necessarily configured to ensure those errors get routed to `stderr`.

Maybe its worth pinging the HDF group about that.
